name: فك الضغط التلقائي
on:
  push:
    paths:
      - 'hotspot5G-redlimited.zip'
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: تحميل المستودع
        uses: actions/checkout@v4
        
      - name: فك الضغط
        run: |
          # إنشاء مجلد للاستخراج
          mkdir ملفات_مستخرجة
          
          # فك الضغط (وضع صامت)
          unzip -q hotspot5G-redlimited.zip -d ملفات_مستخرجة/
          
          # نقل المحتويات للمجلد الرئيسي
          mv ملفات_مستخرجة/* .
          
          # التنظيف
          rm -rf hotspot5G-redlimited.zip ملفات_مستخرجة
          
      - name: حفظ التغييرات
        uses: EndBug/add-and-commit@v9
        with:
          message: "تم فك الضغط تلقائياً"
          add: "."
