name: Unzip hotspot5G-redlimited.zip

on:
  push:
    paths:
      - '.github/workflows/hotspot5G-redlimited.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip hotspot5G-redlimited.zip
        run: |
          unzip -o .github/workflows/hotspot5G-redlimited.zip -d .github/workflows/hotspot5G-redlimited

      - name: Commit unzipped files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .github/workflows/hotspot5G-redlimited/
          git commit -m "Unzipped hotspot5G-redlimited.zip automatically"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
