name: Auto-Unzip
on:
  push:
    paths:
      - 'hotspot5G-redlimited.zip'
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Unzip file
        run: |
          unzip -q hotspot5G-redlimited.zip -d unzipped/
          rm -f hotspot5G-redlimited.zip
          mv unzipped/* .
          rm -rf unzipped
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto-extracted: ${{ github.sha }}"
          add: "."
