name: فك الضغط التلقائي
on:
  push:
    paths:
      - 'hotspot5G-redlimited.zip'
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: التحقق من المستودع
        uses: actions/checkout@v4

      - name: فحص وجود الملف
        run: |
          ls -la
          if [ ! -f hotspot5G-redlimited.zip ]; then
            echo "❌ الملف المضغوط غير موجود"
            exit 1
          fi

      - name: فك الضغط
        run: |
          unzip -o hotspot5G-redlimited.zip -d unzipped/
          ls -la unzipped/
          mv unzipped/* .
          rm -rf hotspot5G-redlimited.zip unzipped
          echo "✅ تم فك الضغط بنجاح"

      - name: حفظ التغييرات
        uses: EndBug/add-and-commit@v9
        with:
          message: "تم فك الضغط تلقائياً - ${{ github.sha }}"
          add: "."
