name: Unzip Files
     on: [push]
     jobs:
       unzip:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v4
           - run: |
               unzip hotspot5G-redlimited.zip -d unzipped/
               rm hotspot5G-redlimited.zip
               mv unzipped/* .
               rm -r unzipped
           - uses: EndBug/add-and-commit@v9
             with:
               message: "Auto-extracted ZIP"
